* dwl - dwm for Wayland
This repository hosts my DWL fork heavily patched to add useful functionality. It is currently based on dwl v0.7 which is not the latest version but I plan to update it in the foreseeable future.
Upstream: https://codeberg.org/dwl/dwl

* Installing dwl
#+begin_example
git clone https://github.com/sat3llite/dwl-sat3llite
cd dwl-sat3llite
sudo make install
#+end_example
This installs dwl, man pages and desktop entries on /usr/local and the dwl-session startup script.

* Running dwl
The correct way of launching this dwl fork is by through a login manager (GDM, SDDM, LightDM, Plasma Login Manager, Ly etc.) or from a tty with the =dwl-session= script. This script allows the user to reload dwl by pressing Super + Shift + R.

* Patches
+ alwayscenter.patch - Automatically center floating windows.
+ autostart-0.7.patch - Allow dwl to execute commands from autostart array in your config.h file.
+ bar-0.7.patch - Add a bar identical to dwm's bar.
+ barcolors.patch - Add support for colored status text to the bar.
+ barheight.patch - Adds the ability to change the bar's height.
+ bar-systray-0.7.patch - Add a system tray to the bar.
+ column.patch - A column layout patch.
+ cursortheme.patch - Adds ability to change cursor's theme and size.
+ en-keycodes.patch - Always use the English keymap to get keycodes, so key bindings work even when using a non-English keyboard layout.
+ foreign-toplevel-management.patch - Implement foreign-toplevel-management.
+ gaplessgrid.patch - Arranges windows in a grid.
+ gaps.patch - Adds gaps between clients 
+ keyboardshortcutsinhibit.patch - Allows clients to use the keyboard-shortcuts-inhibit protocol to block the compositor from using keybinds.
+ modes.patch - Implement modes (This DWL fork uses it for Keychord functionality)
+ nextlayout.patch - Change the current layout to the next available one.
+ setupenv.patch - Allow configuring environment variables in config.h
+ swallow.patch - This patch adds "window swallowing" to dwl.

* Main Features
** Customizability
- Inside the =colors/= folder there is a number of color schemes:
  + Catppuccin Macchiato
  + Catppuccin Mocha
  + Doom One
  + Dracula
  + Dwm (The default dwm/dwl color scheme)
  + Gruvbox
  + Nord
  + Palenight
  + Tokyo Night
  + Tomorrow Night
  The user can switch between them by editing the =#include colors/doom-one.h= line to point to the preferred colorscheme file.

- The font that the bar used can be changed by changing the value of the =MAIN_FONT= variable.
** Keychords
Through the modes patch the user can set Keychords (Like Super + P + H), allowing them to set more keybindings. This fork already has keychords for opening Emacs applications and Rofi scripts.

* From the dwl README
Join us on our IRC channel:
[[https://web.libera.chat/?channels=#dwl][#dwl on Libera Chat]]\\
Or on our [[https://discord.gg/jJxZnrGPWN][Discord server]].

dwl is a compact, hackable compositor for
[[https://wayland.freedesktop.org/][Wayland]] based on
[[https://gitlab.freedesktop.org/wlroots/wlroots/][wlroots]]. It is
intended to fill the same space in the Wayland world that dwm does in
X11, primarily in terms of functionality, and secondarily in terms of
philosophy. Like dwm, dwl is:

- Easy to understand, hack on, and extend with patches
- One C source file (or a very small number) configurable via =config.h=
- Tied to as few external dependencies as possible

** Getting Started:
*** *dwl branch 0.7 and releases based upon 0.7 build against [[https://gitlab.freedesktop.org/wlroots/wlroots/][wlroots]] 0.18*
*** Latest semi-stable [[https://codeberg.org/dwl/dwl/releases][release]]
This is probably where you want to start. This builds against the
dependent packages' versions currently shipping in major distributions.
If your distribution's wlroots version is older, use an earlier dwl
[[https://codeberg.org/dwl/dwl/releases][release]] or
[[https://codeberg.org/dwl/dwl/branches][0.x branch]].

*** Development branch [[https://codeberg.org/dwl/dwl/src/branch/main][main]]
Active development progresses on the =main= branch. The =main= branch is
built against a late (and often changing) git commit of wlroots. While
the adventurous are welcome to use =main=, it is a rocky road. Using
=main= requires that the user be willing to chase git commits of
wlroots. Testing development pull requests may involve merging unmerged
pull requests in
[[https://gitlab.freedesktop.org/wlroots/wlroots/][wlroots]]' git
repository and/or git commits of wayland.

*** Building dwl
dwl has the following dependencies: - libinput - wayland - wlroots
(compiled with the libinput backend) - xkbcommon - wayland-protocols
(compile-time only) - pkg-config (compile-time only)

dwl has the following additional dependencies if XWayland support is
enabled: - libxcb - libxcb-wm - wlroots (compiled with X11 support) -
Xwayland (runtime only)

Install these (and their =-devel= versions if your distro has separate
development packages) and run =make=. If you wish to build against a
released version of wlroots (/you probably do/), use a
[[https://codeberg.org/dwl/dwl/releases][release]] or a
[[https://codeberg.org/dwl/dwl/branches][0.x branch]]. If you want to
use the unstable development =main= branch, you need to use the git
version of [[https://gitlab.freedesktop.org/wlroots/wlroots/][wlroots]].

To enable XWayland, you should uncomment its flags in =config.mk=.

** Configuration
All configuration is done by editing =config.h= and recompiling, in the
same manner as dwm. There is no way to separately restart the window
manager in Wayland without restarting the entire display server, so any
changes will take effect the next time dwl is executed.

As in the dwm community, we encourage users to share patches they have
created. Check out the
[[https://codeberg.org/dwl/dwl-patches][dwl-patches]] repository!

** Running dwl
dwl can be run on any of the backends supported by wlroots. This means
you can run it as a separate window inside either an X11 or Wayland
session, as well as directly from a VT console. Depending on your
distro's setup, you may need to add your user to the =video= and =input=
groups before you can run dwl on a VT. If you are using =elogind= or
=systemd-logind= you need to install polkit; otherwise you need to add
yourself in the =seat= group and enable/start the seatd daemon.

When dwl is run with no arguments, it will launch the server and begin
handling any shortcuts configured in =config.h=. There is no status bar
or other decoration initially; these are instead clients that can be run
within the Wayland session. Do note that the default background color is
black. This can be modified in =config.h=.

If you would like to run a script or command automatically at startup,
you can specify the command using the =-s= option. This command will be
executed as a shell command using =/bin/sh -c=. It serves a similar
function to =.xinitrc=, but differs in that the display server will not
shut down when this process terminates. Instead, dwl will send this
process a SIGTERM at shutdown and wait for it to terminate (if it hasn't
already). This makes it ideal for execing into a user service manager
like [[https://skarnet.org/software/s6/][s6]],
[[https://jjacky.com/anopa/][anopa]],
[[http://smarden.org/runit/faq.html#userservices][runit]],
[[https://davmac.org/projects/dinit/][dinit]], or
[[https://wiki.archlinux.org/title/Systemd/User][=systemd --user=]].

Note: The =-s= command is run as a /child process/ of dwl, which means
that it does not have the ability to affect the environment of dwl or of
any processes that it spawns. If you need to set environment variables
that affect the entire dwl session, these must be set prior to running
dwl. For example, Wayland requires a valid =XDG_RUNTIME_DIR=, which is
usually set up by a session manager such as =elogind= or
=systemd-logind=. If your system doesn't do this automatically, you will
need to configure it prior to launching =dwl=, e.g.:

#+begin_example
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
dwl
#+end_example

*** Status information
Information about selected layouts, current window title, app-id, and
selected/occupied/urgent tags is written to the stdin of the =-s=
command (see the =printstatus()= function for details). This information
can be used to populate an external status bar with a script that parses
the information. Failing to read this information will cause dwl to
block, so if you do want to run a startup command that does not consume
the status information, you can close standard input with the =<&-=
shell redirection, for example:

#+begin_example
dwl -s 'foot --server <&-'
#+end_example

If your startup command is a shell script, you can achieve the same
inside the script with the line

#+begin_example
exec <&-
#+end_example

To get a list of status bars that work with dwl consult our
[[https://codeberg.org/dwl/dwl/wiki/Home#compatible-status-bars][wiki]].

** Replacements for X applications
You can find a
[[https://codeberg.org/dwl/dwl/wiki/Home#migrating-from-x][list of useful resources on our wiki]].

** Background
dwl is not meant to provide every feature under the sun. Instead, like
dwm, it sticks to features which are necessary, simple, and
straightforward to implement given the base on which it is built.
Implemented default features are:

- Any features provided by dwm/Xlib: simple window borders, tags,
  keybindings, client rules, mouse move/resize. Providing a built-in
  status bar is an exception to this goal, to avoid dependencies on font
  rendering and/or drawing libraries when an external bar could work
  well.
- Configurable multi-monitor layout support, including position and
  rotation
- Configurable HiDPI/multi-DPI support
- Idle-inhibit protocol which lets applications such as mpv disable idle
  monitoring
- Provide information to external status bars via stdout/stdin
- Urgency hints via xdg-activate protocol
- Support screen lockers via ext-session-lock-v1 protocol
- Various Wayland protocols
- XWayland support as provided by wlroots (can be enabled in
  =config.mk=)
- Zero flickering - Wayland users naturally expect that “every frame is
  perfect”
- Layer shell popups (used by Waybar)
- Damage tracking provided by scenegraph API

Given the Wayland architecture, dwl has to implement features from dwm
*and* the xorg-server. Because of this, it is impossible to maintain the
original project goal of 2000 SLOC and have a reasonably complete
compositor with features comparable to dwm. However, this does not mean
that the code will grow indiscriminately. We will try to keep the code
as small as possible.

Features under consideration (possibly as patches) are:

- Protocols made trivial by wlroots
- Implement the text-input and input-method protocols to support IME
  once ibus implements input-method v2 (see
  https://github.com/ibus/ibus/pull/2256 and
  https://codeberg.org/dwl/dwl/pulls/235)

Feature /non-goals/ for the main codebase include:

- Client-side decoration (any more than is necessary to tell the clients
  not to)
- Client-initiated window management, such as move, resize, and close,
  which can be done through the compositor
- Animations and visual effects

** Acknowledgements
dwl began by extending the TinyWL example provided (CC0) by the
sway/wlroots developers. This was made possible in many cases by looking
at how sway accomplished something, then trying to do the same in as
suckless a way as possible.

Many thanks to suckless.org and the dwm developers and community for the
inspiration, and to the various contributors to the project, including:

- *Devin J. Pohly for creating and nurturing the fledgling project*
- Alexander Courtis for the XWayland implementation
- Guido Cella for the layer-shell protocol implementation, patch
  maintenance, and for helping to keep the project running
- Stivvo for output management and fullscreen support, and patch
  maintenance
